
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/cakit/scoop/apps/cmake/current/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
