name: Build Sample For Web
on: [push, pull_request]

jobs:
  build-web:
    name: Build demo for Web
    runs-on: ubuntu-latest
    steps:
      - name: Install latest CMake
        run: |
          git clone https://github.com/Kitware/CMake.git
          cd CMake

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git --depth=1
          cd emsdk
          ./emsdk install tot
          ./emsdk activate tot

      - name: Build for web
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake -S . -B build
          cmake --build build --parallel

      - name: Prepare for upload
        run: |
          mkdir _site
          mv build/sdl-min.html _site/index.html
          mv build/sdl-* _site/

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build-web
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
